/*
 *	Make a valid MASM source file from assembly listing generated by MSVC.
 *
 *	Hack necessary to this:
 *

"Unfortunately, assembling with the Microsoft Macro Assembler (MASM) the asm listing file produced by the VS C++ compiler is not supported.
This listing file is not syntactically correct for MASM and is meant for informational purposes only.

I'll get this information added to the documentation of the /Fa (and
/FA) compiler switches."
(Bill Bailey [MSFT] )

[https://developercommunity.visualstudio.com/t/ml-build-error/128522]

Oct 20, 2017

 *
 *	Unconsistencies fixed:
 *		1) Remove all occurrences of "FLAT:"
 *		2) Remove all lines between "pdata segment" / "pdata ends" and "xdata segment" / "xdata ends"
 *
 *	Get .ASM listing file produced by VC++ as a parameter and output to stdout
 */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <ctype.h>


const static int align_rsp_line_num = 9;

static char align_rsp[] =
"\n"
"_TEXT	SEGMENT\n"
"\n"
"; https://github.com/mattifestation/PIC_Bindshell/blob/master/PIC_Bindshell/AdjustStack.asm\n"
"\n"
"; AlignRSP is a simple call stub that ensures that the stack is 16-byte aligned prior\n"
"; to calling the entry point of the payload. This is necessary because 64-bit functions\n"
"; in Windows assume that they were called with 16-byte stack alignment. When amd64\n"
"; shellcode is executed, you can't be assured that you stack is 16-byte aligned. For example,\n"
"; if your shellcode lands with 8-byte stack alignment, any call to a Win32 function will likely\n"
"; crash upon calling any ASM instruction that utilizes XMM registers (which require 16-byte)\n"
"; alignment.\n"
"\n"
"AlignRSP PROC\n"
"    push rsi ; Preserve RSI since we're stomping on it\n"
"    mov rsi, rsp ; Save the value of RSP so it can be restored\n"
"    and rsp, 0FFFFFFFFFFFFFFF0h ; Align RSP to 16 bytes\n"
"    sub rsp, 020h ; Allocate homing space for ExecutePayload\n"
"    call main ; Call the entry point of the payload\n"
"    mov rsp, rsi ; Restore the original value of RSP\n"
"    pop rsi ; Restore RSI\n"
"    ret ; Return to caller\n"
"AlignRSP ENDP\n"
"\n"
"_TEXT	ENDS\n"
"\n"
;

int main(int argc, char **argv)
{
	FILE *f = NULL;
	char line[4096];
	char upcase_line[4096];
	char out_line[4096];
	int i, j;
	char *p = NULL;
	int skipping_lines = 0;
	int line_num = 1;

	if (argc < 2)
	{
		fprintf(stderr, "Missing .ASM file\n");
		exit(-1);
	}

	f = fopen(argv[1], "rb");
	if (!f)
	{
		fprintf(stderr, "Can't open '%s': %s (%d)\n", argv[1], strerror(errno), errno);
		exit(-1);
	}

	while (!feof(f))
	{
		line[0] = '\0';
		out_line[0] = '\0';
		fgets(line, sizeof(line), f);
		if (p = strchr(line, '\r'))
			*p = '\0';
		if (p = strchr(line, '\n'))
			*p = '\0';

		++line_num;

		//-------------------------------------- Process --------------------------------------------
		

		// Convert input line to uppercase for some case-insensitive checks

		i = 0;
		do
		{
			upcase_line[i] = toupper(line[i]);
			++i;
		}
		while (line[i]);

		// Pre-output: if the line contains "pdata" / "xdata" and "segment", output "IF 0" before it
		if ((strstr(upcase_line, "PDATA") || strstr(upcase_line, "XDATA")) && strstr(upcase_line, "SEGMENT"))
			printf("IF 0\n");

		// Remove all occurances of FLAT on current line, case-insensitive
		for (i = 0, j = 0; line[i] != '\0'; ++i, ++j)
		{
			// Skip "FLAT" when copying line[] to out_line[]
			if (!_strnicmp(line + i, "FLAT:", (sizeof("FLAT:") - 1)))
			{
				printf(";********* Found FLAT:\n");
				i += sizeof("FLAT:") - 1;
			}

			out_line[j] = line[i];

		}
		
		out_line[j] = '\0';
		strcpy(line, out_line);
		out_line[0] = '\0';

		if (line_num == align_rsp_line_num)
		{
			printf("%s", align_rsp);
		}

		// Change gs:NNNN -> gs:[NNNN] (actually any segment specifier .s:
		if (p = strstr(line, "s:"))
		{
			char *q = NULL;
			
			memcpy(out_line, line, p + 2 - line);
			p += 2;
			q = out_line + (p - line);

			while (isspace(*p))
				*q++ = *p++;

			if (*p >= '0' && *p <= '9')
			{
				*q++ = '[';
				while (isalnum(*p))
					*q++ = *p++;
				*q++ = ']';
			}
			strcpy(q, p);

			strcpy(line, out_line);
			out_line[0] = '\0';
		}

		// Change INCLUDELIB -> ;INCLUDELIB
		if (strstr(line, "INCLUDELIB"))
		{
			sprintf(out_line, ";%s", line);
			strcpy(line, out_line);
		}

		// Allow inline assembly in MSVC: change "///__asm" to "". Multi-line inline assembly yet to come
		if (p = strstr(line, "///__asm"))
		{
			char *q = p + strlen("///__asm");
			memmove(line, q, strlen(q) + 1);
		}

		printf("%s\n", line);

		// Post-output: if the line contains "pdata" / "xdata" and "ends", output "ENDIF" after it
		if ((strstr(upcase_line, "PDATA") || strstr(upcase_line, "XDATA")) && strstr(upcase_line, "ENDS"))
			printf("ENDIF\n");
	}

	fclose(f);

	return	0;
}
